@extends('layouts.layout-home')

@section('corsoMain')
    <div class="bkg-default text-style">
       <h1>Il corso</h1>
       <p>
        Icing pastry jelly candy dragée powder chocolate cake candy cookie. Jelly fruitcake jelly oat cake. Chocolate jelly beans gummi bears sesame snaps lollipop brownie dessert tart topping. Icing cotton candy biscuit cheesecake halvah sweet roll caramels muffin lemon drops. Cake danish oat cake. Dessert fruitcake candy danish chocolate cake macaroon. Brownie cookie jelly beans. Donut caramels candy marzipan marzipan caramels gummies. Chupa chups brownie jelly-o brownie wafer toffee croissant wafer cake. Fruitcake oat cake lollipop gummies cupcake jelly jelly-o tootsie roll. Marzipan lollipop pudding marzipan. Liquorice cake topping fruitcake.
        Powder carrot cake dragée tiramisu dragée biscuit soufflé sweet cake. Gummi bears cookie powder bear claw. Danish marshmallow cotton candy sugar plum. Gummi bears croissant jelly gummi bears donut lollipop brownie. Bonbon croissant tootsie roll fruitcake. Bonbon cotton candy candy canes marzipan. Soufflé sugar plum bonbon dessert donut. Jelly beans oat cake dragée soufflé. Marzipan halvah pudding dessert jelly. Lemon drops brownie marshmallow chupa chups cupcake. Pastry jelly cupcake gummi bears soufflé chocolate icing wafer brownie. Gummies tootsie roll wafer. Bonbon carrot cake liquorice fruitcake brownie tart sweet roll jelly-o. Dessert cotton candy marzipan jelly beans tart sweet roll cake cotton candy.
        Tart candy canes bonbon macaroon toffee liquorice muffin. Bear claw sweet cake dragée. Macaroon cotton candy biscuit tootsie roll jujubes sweet jujubes chocolate. Muffin sugar plum cake pastry pie jelly-o pudding jelly-o. Jelly sweet fruitcake fruitcake gummi bears. Cheesecake gingerbread macaroon. Dragée marshmallow sweet roll. Gingerbread liquorice marshmallow pie brownie apple pie lemon drops. Chocolate cake toffee pie cotton candy carrot cake. Croissant chocolate powder danish marshmallow. Halvah biscuit powder ice cream. Candy canes lollipop pie.
        Halvah candy canes chocolate bar sweet roll chocolate candy canes. Sweet roll dessert pie liquorice tootsie roll. Toffee toffee pudding icing cake. Bear claw bear claw caramels. Sugar plum lemon drops lemon drops. Pastry gummies pastry sweet. Sesame snaps pie oat cake croissant pastry croissant macaroon. Pudding sesame snaps jelly-o bonbon halvah jujubes gummi bears jelly. Jelly beans cake jujubes jelly-o wafer gummi bears soufflé pastry dessert. Fruitcake gummies topping. Cheesecake lollipop jujubes apple pie. Bonbon candy canes cake jelly croissant topping cake. Jujubes jelly beans pastry.
        Ice cream gingerbread gingerbread biscuit chupa chups caramels lollipop sweet roll. Caramels cotton candy lollipop biscuit cotton candy donut liquorice macaroon jelly beans. Pudding croissant soufflé caramels oat cake powder. Cheesecake bonbon pudding dessert sugar plum. Gummi bears pudding oat cake. Sugar plum gummi bears cupcake halvah liquorice cookie jelly beans danish. Oat cake tiramisu sugar plum gummies jelly. Lollipop gummies candy canes gingerbread. Biscuit marshmallow cake. Oat cake jelly donut donut. Marshmallow croissant topping tiramisu muffin sugar plum brownie. Sweet chocolate cake pudding bear claw cookie halvah jelly-o jelly-o.
       </p>
    </div>
@endsection

